export { default as Dashboard } from './Dashboard';
export { default as Kanban } from './Kanban';
export { default as Orders } from './Orders';
export { default as Employees } from './Employees';
export { default as PersonalProfile } from './PersonalProfile';
// export { default as UserProfile } from './UserProfile';
export { default as AcademicInformation } from './modules/academic/AcademicInformation';
export { default as WorkExperience } from './modules/WorkExperience/WorkExperience';
export { default as CreateJobVacancy } from './modules/JobVacancy/CreateJobVacancy';
export { default as ProfessionalInformation } from './modules/Professional/ProfessionalInformation';
export { default as Referees } from './modules/Referees/Referees';
export { default as CertificationTraining } from './modules/Certification/CertificationTraining';
export { default as ProfessionalBodyMembership } from './modules/Professional/ProfessionalBodyMembership';
export { default as AddUser } from './Admin/Users/AddUser';
// export { default as WorkExperience } from './WorkExperience';
export { default as Editor } from './Editor';
export { default as Customers } from './Customers';
export { default as ColorPicker } from './ColorPicker';
export { default as Calendar } from './Calendar';
export { default as Area } from './Charts/Area';
export { default as Bar } from './Charts/Bar';
export { default as ColorMapping } from './Charts/ColorMapping';
export { default as Financial } from './Charts/Financial';
export { default as Line } from './Charts/Line';
export { default as Pie } from './Charts/Pie';
export { default as Pyramid } from './Charts/Pyramid';
export { default as Stacked } from './Charts/Stacked';

